import { channelImages, videoImg } from "./images";

const videos = [
	{
		videoImage: videoImg,
		channelImage: channelImages.ch1,
		title: "This is a sample video 1.",
		channelName: "Channel Name",
		views: "124k",
		uploaded: "2 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch2,
		title: "This is a sample video 2.",
		channelName: "Channel Name",
		views: "124,90k",
		uploaded: "1 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch3,
		title: "This is a sample video 3.",
		channelName: "Channel Name",
		views: "12.8k",
		uploaded: "4 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch4,
		title: "This is a sample video 4.",
		channelName: "Channel Name",
		views: "14k",
		uploaded: "3 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch1,
		title: "This is a sample video 5.",
		channelName: "Channel Name",
		views: "124k",
		uploaded: "2 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch2,
		title: "This is a sample video 6.",
		channelName: "Channel Name",
		views: "124,90k",
		uploaded: "1 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch3,
		title: "This is a sample video 7.",
		channelName: "Channel Name",
		views: "12.8k",
		uploaded: "4 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch4,
		title: "This is a sample video 8.",
		channelName: "Channel Name",
		views: "14k",
		uploaded: "3 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch1,
		title: "This is a sample video 9.",
		channelName: "Channel Name",
		views: "124k",
		uploaded: "2 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch2,
		title: "This is a sample video 10.",
		channelName: "Channel Name",
		views: "124,90k",
		uploaded: "1 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch3,
		title: "This is a sample video 11.",
		channelName: "Channel Name",
		views: "12.8k",
		uploaded: "4 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch4,
		title: "This is a sample video 12.",
		channelName: "Channel Name",
		views: "14k",
		uploaded: "3 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch1,
		title: "This is a sample video 13.",
		channelName: "Channel Name",
		views: "124k",
		uploaded: "2 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch2,
		title: "This is a sample video 14.",
		channelName: "Channel Name",
		views: "124,90k",
		uploaded: "1 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch3,
		title: "This is a sample video 15.",
		channelName: "Channel Name",
		views: "12.8k",
		uploaded: "4 weeks ago",
	},
	{
		videoImage: videoImg,
		channelImage: channelImages.ch4,
		title: "This is a sample video 16.",
		channelName: "Channel Name",
		views: "14k",
		uploaded: "3 weeks ago",
	},
];

export { videos };
